package cli

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
)

const postCheckoutHookScript = `#!/bin/sh
# Git post-checkout hook generated by git-meta
echo "🔍 git-meta: Checking submodule branch alignment..."
git meta status --server http://localhost:8080 || true
`

const preCommitHookScript = `#!/bin/sh
# Git pre-commit hook generated by git-meta
echo "🔍 git-meta: Verifying submodule state before commit..."
# Enforce that no submodules are in a detached HEAD state with uncommitted changes
git submodule foreach '
  if ! git symbolic-ref -q HEAD > /dev/null; then
    echo "❌ ERROR: Submodule $name is in a detached HEAD state!"
    exit 1
  fi
'
`

func InstallHooks(rootDir string) error {
	hooksDir := filepath.Join(rootDir, ".git", "hooks")

	if _, err := os.Stat(hooksDir); os.IsNotExist(err) {
		return fmt.Errorf("not inside a git repository (.git/hooks directory not found)")
	}

	postCheckoutPath := filepath.Join(hooksDir, "post-checkout")
	preCommitPath := filepath.Join(hooksDir, "pre-commit")

	if err := os.WriteFile(postCheckoutPath, []byte(postCheckoutHookScript), 0755); err != nil {
		return fmt.Errorf("failed to write post-checkout hook: %w", err)
	}

	if err := os.WriteFile(preCommitPath, []byte(preCommitHookScript), 0755); err != nil {
		return fmt.Errorf("failed to write pre-commit hook: %w", err)
	}

	return nil
}

func newInstallHooksCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "install-hooks",
		Short: "Install git-meta post-checkout and pre-commit hooks into .git/hooks",
		RunE: func(cmd *cobra.Command, args []string) error {
			cwd, err := os.Getwd()
			if err != nil {
				return err
			}
			if err := InstallHooks(cwd); err != nil {
				return err
			}
			fmt.Println("✅ git-meta post-checkout and pre-commit hooks installed successfully!")
			return nil
		},
	}
}
